name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug GitLab Token
        run: |
          echo "GitLab Token: ${{ secrets.GITLAB_TOKEN }}"

      - name: Debug Git Remote
        run: |
          git remote -v

      - name: Push to GitLab
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/jerryben/user-service.git
          git push gitlab main
